import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../models/reading.dart';

class PdfService {
  
  // 1. Build the PDF Document (Internal Helper)
  Future<pw.Document> _generateDocument(List<Reading> readings) async {
    final pdf = pw.Document();
    final font = await PdfGoogleFonts.poppinsRegular();
    final boldFont = await PdfGoogleFonts.poppinsBold();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text("Blood Pressure Report", style: pw.TextStyle(font: boldFont, fontSize: 24)),
                  pw.Text(DateFormat('MMM d, yyyy').format(DateTime.now()), style: pw.TextStyle(font: font, fontSize: 18)),
                ],
              ),
            ),
            pw.SizedBox(height: 20),
            pw.Table.fromTextArray(
              context: context,
              border: null,
              headerStyle: pw.TextStyle(font: boldFont, color: PdfColors.white),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.red900),
              cellHeight: 30,
              cellAlignments: {
                0: pw.Alignment.centerLeft,
                1: pw.Alignment.center,
                2: pw.Alignment.center,
                3: pw.Alignment.center,
                4: pw.Alignment.center,
              },
              headers: ['Date', 'Period', 'BP (mmHg)', 'Pulse', 'Meds'],
              data: readings.map((r) {
                return [
                  DateFormat('MMM d, h:mm a').format(r.createdAt),
                  r.period,
                  "${r.sys}/${r.dia}",
                  "${r.pulse}",
                  r.medication ? "Yes" : "-"
                ];
              }).toList(),
            ),
            pw.Padding(padding: const pw.EdgeInsets.all(20)),
            pw.Text("Generated by PressurePal", style: pw.TextStyle(font: font, fontSize: 12, color: PdfColors.grey)),
          ];
        },
      ),
    );
    return pdf;
  }

  // 2. Original Print Function (Keep for backward compatibility)
  Future<void> printReport(List<Reading> readings) async {
    final pdf = await _generateDocument(readings);
    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());
  }

  // 3. NEW: Share PDF Function
  Future<void> shareReport(List<Reading> readings) async {
    final pdf = await _generateDocument(readings);
    
    // Save to temp file
    final output = await getTemporaryDirectory();
    final file = File("${output.path}/bp_report.pdf");
    await file.writeAsBytes(await pdf.save());

    // Share via WhatsApp/Email
    await Share.shareXFiles([XFile(file.path)], text: 'Here is my Blood Pressure PDF Report.');
  }
}